// Service worker de DescriptIA: cachea todos los archivos para que la app
// se pueda instalar y funcione sin conexión. Para publicar una actualización,
// sube el número de versión (CACHE) y se refrescará en el siguiente arranque.
// CACHE y APP_VERSION (js/nucleo/arranque.js) van unificados desde v4.9.0.
const CACHE = "fiesta-v5.2.0";

const ARCHIVOS = [
  "./",
  "./index.html",
  "./css/estilos.css",
  "./js/nucleo/pantallas.js",
  "./js/nucleo/util.js",
  "./js/nucleo/arranque.js",
  "./js/descriptia/estado.js",
  "./js/descriptia/datos.js",
  "./js/descriptia/juego.js",
  "./js/descriptia/main.js",
  "./js/cartas/main.js",
  "./js/ruleta/main.js",
  "./js/zona/main.js",
  "./js/zona/noche.js",
  "./js/zona/dia.js",
  "./js/blackjack/motor.js",
  "./js/blackjack/tarot.js",
  "./js/blackjack/clasico.js",
  "./js/blackjack/animaciones.js",
  "./js/blackjack/arcade.js",
  "./js/blackjack/estadisticas.js",
  "./js/blackjack/main.js",
  "./data/ruleta/tematicas.js",
  "./data/descriptia/tarjetas.js",
  "./data/cartas/efectos.js",
  "./data/zona/roles.js",
  "./data/zona/textos.js",
  "./data/blackjack/reglas.js",
  "./data/blackjack/tarot.js",
  "./site.webmanifest",
  "./icons/icono.svg",
  "./icons/icon-180.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  // Cartas de la Fortuna: reverso + 40 españolas + 6 tarot (para jugar offline)
  "./img/cartas/reverso.png",
  "./img/cartas/oros-1.png",
  "./img/cartas/oros-2.png",
  "./img/cartas/oros-3.png",
  "./img/cartas/oros-4.png",
  "./img/cartas/oros-5.png",
  "./img/cartas/oros-6.png",
  "./img/cartas/oros-7.png",
  "./img/cartas/oros-sota.png",
  "./img/cartas/oros-caballo.png",
  "./img/cartas/oros-rey.png",
  "./img/cartas/copas-1.png",
  "./img/cartas/copas-2.png",
  "./img/cartas/copas-3.png",
  "./img/cartas/copas-4.png",
  "./img/cartas/copas-5.png",
  "./img/cartas/copas-6.png",
  "./img/cartas/copas-7.png",
  "./img/cartas/copas-sota.png",
  "./img/cartas/copas-caballo.png",
  "./img/cartas/copas-rey.png",
  "./img/cartas/espadas-1.png",
  "./img/cartas/espadas-2.png",
  "./img/cartas/espadas-3.png",
  "./img/cartas/espadas-4.png",
  "./img/cartas/espadas-5.png",
  "./img/cartas/espadas-6.png",
  "./img/cartas/espadas-7.png",
  "./img/cartas/espadas-sota.png",
  "./img/cartas/espadas-caballo.png",
  "./img/cartas/espadas-rey.png",
  "./img/cartas/bastos-1.png",
  "./img/cartas/bastos-2.png",
  "./img/cartas/bastos-3.png",
  "./img/cartas/bastos-4.png",
  "./img/cartas/bastos-5.png",
  "./img/cartas/bastos-6.png",
  "./img/cartas/bastos-7.png",
  "./img/cartas/bastos-sota.png",
  "./img/cartas/bastos-caballo.png",
  "./img/cartas/bastos-rey.png",
  "./img/cartas/tarot-diablo.png",
  "./img/cartas/tarot-diablo-invertida.png",
  "./img/cartas/tarot-loco.png",
  "./img/cartas/tarot-loco-invertida.png",
  "./img/cartas/tarot-rueda.png",
  "./img/cartas/tarot-rueda-invertida.png",
  // 21 Arcanos: baraja de poker (52 + reverso propio, Fase 1)
  "./img/21arc/poker-reverso.png",
  "./img/21arc/poker-picas-A.png",
  "./img/21arc/poker-picas-2.png",
  "./img/21arc/poker-picas-3.png",
  "./img/21arc/poker-picas-4.png",
  "./img/21arc/poker-picas-5.png",
  "./img/21arc/poker-picas-6.png",
  "./img/21arc/poker-picas-7.png",
  "./img/21arc/poker-picas-8.png",
  "./img/21arc/poker-picas-9.png",
  "./img/21arc/poker-picas-10.png",
  "./img/21arc/poker-picas-J.png",
  "./img/21arc/poker-picas-Q.png",
  "./img/21arc/poker-picas-K.png",
  "./img/21arc/poker-corazones-A.png",
  "./img/21arc/poker-corazones-2.png",
  "./img/21arc/poker-corazones-3.png",
  "./img/21arc/poker-corazones-4.png",
  "./img/21arc/poker-corazones-5.png",
  "./img/21arc/poker-corazones-6.png",
  "./img/21arc/poker-corazones-7.png",
  "./img/21arc/poker-corazones-8.png",
  "./img/21arc/poker-corazones-9.png",
  "./img/21arc/poker-corazones-10.png",
  "./img/21arc/poker-corazones-J.png",
  "./img/21arc/poker-corazones-Q.png",
  "./img/21arc/poker-corazones-K.png",
  "./img/21arc/poker-diamantes-A.png",
  "./img/21arc/poker-diamantes-2.png",
  "./img/21arc/poker-diamantes-3.png",
  "./img/21arc/poker-diamantes-4.png",
  "./img/21arc/poker-diamantes-5.png",
  "./img/21arc/poker-diamantes-6.png",
  "./img/21arc/poker-diamantes-7.png",
  "./img/21arc/poker-diamantes-8.png",
  "./img/21arc/poker-diamantes-9.png",
  "./img/21arc/poker-diamantes-10.png",
  "./img/21arc/poker-diamantes-J.png",
  "./img/21arc/poker-diamantes-Q.png",
  "./img/21arc/poker-diamantes-K.png",
  "./img/21arc/poker-treboles-A.png",
  "./img/21arc/poker-treboles-2.png",
  "./img/21arc/poker-treboles-3.png",
  "./img/21arc/poker-treboles-4.png",
  "./img/21arc/poker-treboles-5.png",
  "./img/21arc/poker-treboles-6.png",
  "./img/21arc/poker-treboles-7.png",
  "./img/21arc/poker-treboles-8.png",
  "./img/21arc/poker-treboles-9.png",
  "./img/21arc/poker-treboles-10.png",
  "./img/21arc/poker-treboles-J.png",
  "./img/21arc/poker-treboles-Q.png",
  "./img/21arc/poker-treboles-K.png",
  // 21 Arcanos: tarot negro/dorado, 22 arcanos x (normal + invertida)
  "./img/21arc/tarot-bj-loco.png",
  "./img/21arc/tarot-bj-loco-invertida.png",
  "./img/21arc/tarot-bj-mago.png",
  "./img/21arc/tarot-bj-mago-invertida.png",
  "./img/21arc/tarot-bj-sacerdotisa.png",
  "./img/21arc/tarot-bj-sacerdotisa-invertida.png",
  "./img/21arc/tarot-bj-emperatriz.png",
  "./img/21arc/tarot-bj-emperatriz-invertida.png",
  "./img/21arc/tarot-bj-emperador.png",
  "./img/21arc/tarot-bj-emperador-invertida.png",
  "./img/21arc/tarot-bj-hierofante.png",
  "./img/21arc/tarot-bj-hierofante-invertida.png",
  "./img/21arc/tarot-bj-enamorados.png",
  "./img/21arc/tarot-bj-enamorados-invertida.png",
  "./img/21arc/tarot-bj-carro.png",
  "./img/21arc/tarot-bj-carro-invertida.png",
  "./img/21arc/tarot-bj-fuerza.png",
  "./img/21arc/tarot-bj-fuerza-invertida.png",
  "./img/21arc/tarot-bj-ermitano.png",
  "./img/21arc/tarot-bj-ermitano-invertida.png",
  "./img/21arc/tarot-bj-rueda.png",
  "./img/21arc/tarot-bj-rueda-invertida.png",
  "./img/21arc/tarot-bj-justicia.png",
  "./img/21arc/tarot-bj-justicia-invertida.png",
  "./img/21arc/tarot-bj-colgado.png",
  "./img/21arc/tarot-bj-colgado-invertida.png",
  "./img/21arc/tarot-bj-muerte.png",
  "./img/21arc/tarot-bj-muerte-invertida.png",
  "./img/21arc/tarot-bj-templanza.png",
  "./img/21arc/tarot-bj-templanza-invertida.png",
  "./img/21arc/tarot-bj-diablo.png",
  "./img/21arc/tarot-bj-diablo-invertida.png",
  "./img/21arc/tarot-bj-torre.png",
  "./img/21arc/tarot-bj-torre-invertida.png",
  "./img/21arc/tarot-bj-estrella.png",
  "./img/21arc/tarot-bj-estrella-invertida.png",
  "./img/21arc/tarot-bj-luna.png",
  "./img/21arc/tarot-bj-luna-invertida.png",
  "./img/21arc/tarot-bj-sol.png",
  "./img/21arc/tarot-bj-sol-invertida.png",
  "./img/21arc/tarot-bj-juicio.png",
  "./img/21arc/tarot-bj-juicio-invertida.png",
  "./img/21arc/tarot-bj-mundo.png",
  "./img/21arc/tarot-bj-mundo-invertida.png",
  // Zona Tensionada: cartas de los roles + reverso (Fase 0)
  "./img/zona/reverso.png",
  "./img/zona/buitre.png",
  "./img/zona/plataforma.png",
  "./img/zona/hacienda.png",
  "./img/zona/sindicato.png",
  "./img/zona/okupa.png",
  "./img/zona/tasador.png",
  "./img/zona/inmobiliaria.png",
  "./img/zona/influencer.png",
  "./img/zona/vecino-1.png",
  "./img/zona/vecino-2.png",
  "./img/zona/vecino-3.png",
  "./img/zona/vecino-4.png",
  "./img/zona/vecino-5.png",
];

// Al instalar: guardar todos los archivos en caché.
self.addEventListener("install", (evento) => {
  evento.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(ARCHIVOS)).then(() => self.skipWaiting())
  );
});

// Al activar: borrar cachés de versiones antiguas.
self.addEventListener("activate", (evento) => {
  evento.waitUntil(
    caches
      .keys()
      .then((claves) =>
        Promise.all(claves.filter((c) => c !== CACHE).map((c) => caches.delete(c)))
      )
      .then(() => self.clients.claim())
  );
});

// Al pedir un recurso: servir de la caché y, si no está, ir a la red.
self.addEventListener("fetch", (evento) => {
  if (evento.request.method !== "GET") return;
  evento.respondWith(
    caches.match(evento.request).then((cacheado) => {
      return (
        cacheado ||
        fetch(evento.request).catch(() => caches.match("./index.html"))
      );
    })
  );
});
